# Generated by Django 4.2.4 on 2023-12-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="produtos",
            fields=[
                ("id_produto", models.AutoField(primary_key=True, serialize=True)),
                ("nome", models.TextField(max_length=255)),
                ("quantidade", models.IntegerField()),
                ("valor", models.IntegerField()),
                ("validade", models.TextField()),
                ("lucro", models.DateField()),
                ("img", models.ImageField(upload_to="/imgs")),
            ],
        ),
    ]
