# Generated by Django 4.2.4 on 2023-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_PDI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="lucro",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="validade",
            field=models.TextField(),
        ),
    ]
