# Generated by Django 4.2.4 on 2023-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_PDI", "0002_alter_produtos_lucro_alter_produtos_validade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="id_produto",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="img",
            field=models.ImageField(upload_to="imgs"),
        ),
    ]
