# Generated by Django 4.2.4 on 2023-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_PDI", "0003_alter_produtos_id_produto_alter_produtos_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="img",
            field=models.ImageField(upload_to=""),
        ),
    ]
