# Generated by Django 5.0 on 2023-12-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PDI', '0004_alter_produtos_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_pessosal', models.ImageField(upload_to='')),
                ('nome', models.TextField(max_length=255)),
                ('CPF', models.TextField(max_length=255)),
                ('RG', models.TextField(max_length=255)),
                ('PIS_Pasep', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('comprovante_residencia', models.ImageField(upload_to='')),
                ('comprovante_escolaridade', models.ImageField(upload_to='')),
                ('curriculo', models.ImageField(upload_to='')),
                ('CTPS', models.CharField(max_length=255)),
                ('cargo', models.TextField(max_length=255)),
                ('salario', models.IntegerField()),
                ('efetivado', models.DateField()),
                ('departamento', models.CharField(max_length=255)),
                ('situacao', models.CharField(max_length=255)),
                ('endereco', models.TextField(max_length=255)),
                ('numero_contato1', models.CharField(max_length=15)),
                ('numero_contato2', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='lot',
            field=models.IntegerField(default=0),
        ),
    ]
